apiVersion: apps/v1
kind: Deployment
metadata:
  name: practice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: practice
  template:
    metadata:
      labels:
        app: practice
    spec:
      containers:
        - name: practice
          image: practice:1.0
          ports:
            - containerPort: 8080
          env:
            - name: PRACTICE_FOO
              value: "FOO"
            - name: PRACTICE_BAR
              value: "BAR"